// books5.js — TomeOcean Extended Catalog Part 5
const BOOKS_PART5 = [
  // DYSTOPIAN
  { id:301, title:"The Handmaid's Tale", author:"Margaret Atwood", isbn:"9780385490818",
    genres:[18,11,7], themes:[0,4,7], year:1985, pages:311, avgRating:4.12,
    description:"In the theocratic Republic of Gilead, fertile women called Handmaids are forced into servitude. Atwood's devastating, prophetic feminist masterpiece." },
  { id:302, title:"We", author:"Yevgeny Zamyatin", isbn:"9780140185852",
    genres:[18,1], themes:[0,4,7], year:1924, pages:240, avgRating:3.79,
    description:"The original dystopian novel that inspired Huxley and Orwell — citizens living in a glass city, overseen by the all-seeing Benefactor." },
  { id:303, title:"Parable of the Sower", author:"Octavia Butler", isbn:"9781538732182",
    genres:[18,1,11], themes:[0,5,7], year:1993, pages:352, avgRating:4.29,
    description:"In a crumbling near-future California, a Black teenager creates a new faith called Earthseed and leads survivors north in a harrowing road novel." },
  { id:304, title:"Station Eleven", author:"Emily St. John Mandel", isbn:"9780804172448",
    genres:[18,11,17], themes:[0,2,8], year:2014, pages:333, avgRating:3.82,
    description:"A pandemic kills most of civilisation. Twenty years later, a travelling Shakespeare company navigates the Great Lakes region — art sustains what science built." },
  { id:305, title:"The Road to Serfdom", author:"F.A. Hayek", isbn:"9780226320618",
    genres:[14,9,6], themes:[4,7], year:1944, pages:274, avgRating:4.12,
    description:"Hayek's influential argument that central economic planning leads inevitably to totalitarianism, written in wartime Britain as a warning to the West." },
  // MORE FANTASY
  { id:306, title:"The Way of Shadows", author:"Brent Weeks", isbn:"9780316033671",
    genres:[2,17], themes:[0,3,6], year:2008, pages:645, avgRating:4.29,
    description:"A street boy apprentices to the world's most dangerous assassin in a city of political intrigue, magic, and brutal violence." },
  { id:307, title:"Cold Days", author:"Jim Butcher", isbn:"9780451464415",
    genres:[2,3,10], themes:[0,3,6], year:2012, pages:532, avgRating:4.38,
    description:"In the 14th Dresden Files novel, Harry Dresden becomes the Winter Knight and must stop an apocalyptic threat on Halloween night in Chicago." },
  { id:308, title:"A Wizard of Earthsea", author:"Ursula K. Le Guin", isbn:"9780547773742",
    genres:[2,17,12], themes:[0,4,8], year:1968, pages:183, avgRating:4.02,
    description:"A young boy discovers his gift for magic and attends school on a magical island — but conjures a terrifying shadow that pursues him across the seas." },
  { id:309, title:"Prince of Thorns", author:"Mark Lawrence", isbn:"9780441020751",
    genres:[2,17], themes:[0,3,7], year:2011, pages:338, avgRating:3.87,
    description:"A murderous 14-year-old prince leads a band of outlaws through the ruins of a future-post-medieval Europe in this shockingly dark debut." },
  { id:310, title:"Warbreaker", author:"Brandon Sanderson", isbn:"9780765360038",
    genres:[2,17], themes:[0,2,4], year:2009, pages:592, avgRating:4.16,
    description:"Two princesses are sent to a foreign court, one to marry a dangerous god-king. Sanderson's magic system uses breath and colour to spectacular effect." },
  { id:311, title:"The Stormlight Archive: Oathbringer", author:"Brandon Sanderson", isbn:"9780765326379",
    genres:[2,17], themes:[0,3,4], year:2017, pages:1248, avgRating:4.70,
    description:"The third Stormlight book follows Dalinar Kholin as he tries to unite the world — while carrying the terrible secret of what he did at the Rift." },
  { id:312, title:"Rhythm of War", author:"Brandon Sanderson", isbn:"9780765326386",
    genres:[2,17], themes:[0,3,4], year:2020, pages:1232, avgRating:4.64,
    description:"Navani and Raboniel race to unlock the secrets of a tower powered by ancient Fabrials while Kaladin confronts his darkest hours yet." },
  { id:313, title:"The Bear and the Nightingale", author:"Katherine Arden", isbn:"9781101885956",
    genres:[2,13], themes:[0,2,8], year:2017, pages:323, avgRating:4.08,
    description:"A girl in medieval Rus must save her village from the dark spirits her stepmother's Christianity is driving away — lush Slavic folklore fantasy." },
  { id:314, title:"Spinning Silver", author:"Naomi Novik", isbn:"9780399180996",
    genres:[2,5,13], themes:[0,2,6], year:2018, pages:480, avgRating:4.04,
    description:"A moneylender's daughter gains power over a demon king through her skill with silver in this gorgeous Rumpelstiltskin-inspired fairy tale retelling." },
  { id:315, title:"The Cruel Prince", author:"Holly Black", isbn:"9780316310321",
    genres:[2,12,5], themes:[0,2,3], year:2018, pages:370, avgRating:4.11,
    description:"A human girl raised in Faerie does everything she can to belong — including plotting against the most dangerous of all the faerie princes." },
  // MORE SCI-FI
  { id:316, title:"Ringworld", author:"Larry Niven", isbn:"9780345333926",
    genres:[1,17], themes:[3,4,8], year:1970, pages:342, avgRating:3.87,
    description:"A trillion-mile-long artificial ring orbiting a distant star — and four explorers who must discover who built it before it destroys them." },
  { id:317, title:"Gateway", author:"Frederik Pohl", isbn:"9780345475831",
    genres:[1,17], themes:[0,4,6], year:1977, pages:313, avgRating:4.03,
    description:"Desperate miners gamble on alien spaceships preprogrammed to reach unknown destinations — most never come back. A pioneering psychological sci-fi." },
  { id:318, title:"Rendezvous with Rama", author:"Arthur C. Clarke", isbn:"9780586213087",
    genres:[1,17], themes:[0,3,4], year:1973, pages:243, avgRating:3.99,
    description:"A vast cylindrical spacecraft enters the solar system and a team of astronauts boards it — with only a few weeks to unlock its secrets." },
  { id:319, title:"The Stars My Destination", author:"Alfred Bester", isbn:"9780679767800",
    genres:[1,18,3], themes:[0,3,7], year:1956, pages:210, avgRating:4.22,
    description:"In a future where teleportation is commonplace, a marooned sailor becomes an obsessive revenger in this proto-cyberpunk classic cited by Gibson and Dick alike." },
  { id:320, title:"Do Androids Dream of Electric Sheep?", author:"Philip K. Dick", isbn:"9780345404473",
    genres:[1,18], themes:[0,4,8], year:1968, pages:244, avgRating:4.04,
    description:"The basis for Blade Runner. A bounty hunter retires rogue androids in a post-nuclear future California, unable to distinguish empathy from simulation." },
  { id:321, title:"The Man in the High Castle", author:"Philip K. Dick", isbn:"9780547572482",
    genres:[1,13,18], themes:[0,4,7], year:1962, pages:259, avgRating:3.75,
    description:"WWII was lost by the Allies. America is occupied by Germany and Japan. Inside this world, a novel circulates depicting another reality — ours." },
  { id:322, title:"Solaris", author:"Stanisław Lem", isbn:"9780156027601",
    genres:[1,15], themes:[0,4,8], year:1961, pages:224, avgRating:3.97,
    description:"Scientists orbiting a sentient ocean-world discover it projects simulations of their deepest memories — a profound inquiry into the limits of human understanding." },
  { id:323, title:"The Moon is a Harsh Mistress", author:"Robert A. Heinlein", isbn:"9780312863555",
    genres:[1,18,7], themes:[0,3,7], year:1966, pages:382, avgRating:4.12,
    description:"A lunar penal colony revolts against Earth — with the help of a self-aware supercomputer. A libertarian space revolution epic." },
  // MORE MYSTERY / CRIME
  { id:324, title:"The Devotion of Suspect X", author:"Keigo Higashino", isbn:"9780312659240",
    genres:[3,4], themes:[0,6,2], year:2005, pages:298, avgRating:4.12,
    description:"A physics genius helps his neighbour cover up a murder — then a brilliant detective closes in. One of Japan's most beloved crime novels." },
  { id:325, title:"Rebecca", author:"Daphne du Maurier", isbn:"9780380730407",
    genres:[3,5,10], themes:[0,2,6], year:1938, pages:449, avgRating:4.24,
    description:"A young bride arrives at Manderley, her husband's magnificent estate — only to find it haunted by the memory of his impossibly glamorous first wife Rebecca." },
  { id:326, title:"Murder on the Orient Express", author:"Agatha Christie", isbn:"9780062073501",
    genres:[3], themes:[0,4,6], year:1934, pages:256, avgRating:4.20,
    description:"Hercule Poirot is stranded on the Orient Express when a murder occurs — every one of the twelve suspects has the perfect motive and the perfect alibi." },
  { id:327, title:"The ABC Murders", author:"Agatha Christie", isbn:"9780062562487",
    genres:[3], themes:[0,4,6], year:1936, pages:256, avgRating:4.10,
    description:"A killer taunts Poirot with ABC Railway Guides before each murder — victims with initials in alphabetical order. Agatha Christie at her most ingenious." },
  { id:328, title:"Tinker, Tailor, Soldier, Spy", author:"John le Carré", isbn:"9780143119784",
    genres:[4,3,9], themes:[0,4,7], year:1974, pages:355, avgRating:4.09,
    description:"A retired spy is brought back to find a Soviet mole at the top of British intelligence. Cold War espionage at its most convincingly grey and moral." },
  { id:329, title:"The Talented Mr. Ripley", author:"Patricia Highsmith", isbn:"9780393332148",
    genres:[3,4], themes:[0,6,2], year:1955, pages:295, avgRating:4.03,
    description:"Tom Ripley travels to Europe to retrieve a millionaire's son and instead assumes his identity in this suave, sinister psychological thriller." },
  { id:330, title:"Shibumi", author:"Trevanian", isbn:"9780312945282",
    genres:[4,3,17], themes:[0,3,4], year:1979, pages:374, avgRating:4.12,
    description:"One of the world's most dangerous assassins is forced back into action in a story that spans WWII, the Cold War, and the caves of the Basque country." },
  // MORE BIOGRAPHY / NON-FICTION
  { id:331, title:"The Diary of a Young Girl", author:"Anne Frank", isbn:"9780553577129",
    genres:[7,13], themes:[0,5], year:1947, pages:283, avgRating:4.19,
    description:"The astonishingly vivid diary kept by a Jewish girl in hiding during the Nazi occupation. One of the most widely read documents of the 20th century." },
  { id:332, title:"Kitchen Confidential", author:"Anthony Bourdain", isbn:"9780060934910",
    genres:[7,6], themes:[1,0,5], year:2000, pages:312, avgRating:4.23,
    description:"Bourdain takes readers behind the scenes of professional kitchens — a raw, profane, funny, and electrifying memoir from the great culinary explorer." },
  { id:333, title:"The Right Stuff", author:"Tom Wolfe", isbn:"9780312427566",
    genres:[9,7,6], themes:[3,4,5], year:1979, pages:436, avgRating:4.25,
    description:"The story of America's first astronauts and test pilots — the elite brotherhood who risked everything in the race to dominate the skies and then space." },
  { id:334, title:"Into the Wild", author:"Jon Krakauer", isbn:"9780385486804",
    genres:[17,7,0], themes:[0,5,8], year:1996, pages:207, avgRating:3.99,
    description:"Christopher McCandless abandons everything and walks into the Alaskan wilderness. Krakauer traces his journey in this haunting meditation on solitude." },
  { id:335, title:"My Brilliant Friend", author:"Elena Ferrante", isbn:"9781609450786",
    genres:[7,11,13], themes:[0,2,9], year:2011, pages:336, avgRating:4.02,
    description:"Two girls grow up in a violent, impoverished Naples neighbourhood — the first in Ferrante's Neapolitan Quartet, one of the great modern epics of female friendship." },
  // MORE HISTORY / SCIENCE
  { id:336, title:"The Order of Time", author:"Carlo Rovelli", isbn:"9780735216105",
    genres:[15,14,6], themes:[4,8], year:2017, pages:224, avgRating:4.05,
    description:"A theoretical physicist reveals how time dissolves at the quantum level — neither past nor future exists. A poetic, mind-expanding rethinking of reality." },
  { id:337, title:"Why We Sleep", author:"Matthew Walker", isbn:"9781501144325",
    genres:[15,16,6], themes:[4,5], year:2017, pages:368, avgRating:4.07,
    description:"A sleep scientist reveals the catastrophic consequences of sleeplessness and the astonishing benefits of a full night's rest in this eye-opening manifesto." },
  { id:338, title:"The Emperor of All Maladies", author:"Siddhartha Mukherjee", isbn:"9781439170915",
    genres:[15,7,6], themes:[0,4,5], year:2010, pages:592, avgRating:4.40,
    description:"A biography of cancer itself — from ancient Egypt to the latest immunotherapy breakthroughs — the Pulitzer Prize-winning book that changed oncology." },
  { id:339, title:"Thinking in Systems", author:"Donella H. Meadows", isbn:"9781603580557",
    genres:[15,6,8], themes:[4,7], year:2008, pages:218, avgRating:4.23,
    description:"An introduction to systems thinking — the single most transformative intellectual framework for understanding why the world behaves as it does." },
  { id:340, title:"The Intelligence Trap", author:"David Robson", isbn:"9780393651423",
    genres:[16,6], themes:[4,5], year:2019, pages:352, avgRating:3.73,
    description:"Why smart people make dumb mistakes — exploring the surprising evidence that intelligence is no protection against poor judgment and self-delusion." },
  // MORE SELF-HELP
  { id:341, title:"Never Split the Difference", author:"Chris Voss", isbn:"9780062407801",
    genres:[8,6], themes:[4,5,3], year:2016, pages:274, avgRating:4.37,
    description:"A former FBI hostage negotiator reveals counterintuitive negotiation tactics — tools that can transform every conversation you'll ever have." },
  { id:342, title:"The Lean Startup", author:"Eric Ries", isbn:"9780307887894",
    genres:[8,6], themes:[4,5], year:2011, pages:336, avgRating:3.97,
    description:"How to build validated learning and rapid experimentation into any organisation — the methodology that changed how Silicon Valley builds companies." },
  { id:343, title:"Thinking, Fast and Slow (Extended)", author:"Daniel Kahneman", isbn:"9780141033570",
    genres:[16,8], themes:[4], year:2011, pages:499, avgRating:4.18,
    description:"Our two cognitive systems — fast intuitive emotional thinking and slow deliberate logical thinking — and their profound influence on every decision we make." },
  { id:344, title:"Can't Hurt Me", author:"David Goggins", isbn:"9781544512280",
    genres:[8,7], themes:[0,5,3], year:2018, pages:364, avgRating:4.43,
    description:"A Navy SEAL, ultramarathon runner, and record-holder shares his transformative philosophy of mental toughness through harrowing personal experience." },
  { id:345, title:"The Courage to Be Disliked", author:"Ichiro Kishimi", isbn:"9781501197277",
    genres:[8,14,16], themes:[4,5,8], year:2013, pages:288, avgRating:4.06,
    description:"A Socratic dialogue between a philosopher and a youth exploring Alfred Adler's ideas: happiness is not determined by the past but by our chosen responses." },
  // MORE ROMANCE (CONTEMPORARY)
  { id:346, title:"The Hating Game", author:"Sally Thorne", isbn:"9780062439598",
    genres:[5,0], themes:[2,1,4], year:2016, pages:374, avgRating:3.97,
    description:"Two rival assistants at a publishing company — one prim and one infuriating — are eventually forced to compete for the same promotion. And then other things happen." },
  { id:347, title:"Normal People", author:"Sally Rooney", isbn:"9780571334650",
    genres:[5,11,12], themes:[0,2,9], year:2018, pages:273, avgRating:3.72,
    description:"Connell and Marianne navigate a complicated will-they-won't-they relationship from school to college in modern Ireland. Raw, brilliant, painful." },
  { id:348, title:"People We Meet on Vacation", author:"Emily Henry", isbn:"9780593334010",
    genres:[5,0], themes:[2,1,9], year:2021, pages:357, avgRating:3.88,
    description:"Alex and Poppy are best friends who ruined everything by sleeping together two summers ago — on a road trip to try again, they revisit every awkward memory." },
  { id:349, title:"The Spanish Love Deception", author:"Elena Armas", isbn:"9781982177010",
    genres:[5,0], themes:[2,1,9], year:2021, pages:415, avgRating:3.77,
    description:"A woman needs a date for her sister's wedding in Spain. Her annoying colleague offers to go. It's fake. Except everything about it feels real." },
  { id:350, title:"Happy Place", author:"Emily Henry", isbn:"9780593441282",
    genres:[5,0], themes:[2,1,9], year:2023, pages:400, avgRating:3.87,
    description:"Two exes have been keeping their breakup secret from friends. Now they're forced to share a cottage in Maine and keep pretending for one last summer." },
  // MORE YA
  { id:351, title:"Shadow and Bone", author:"Leigh Bardugo", isbn:"9780805094596",
    genres:[12,2,17], themes:[0,2,3], year:2012, pages:358, avgRating:3.94,
    description:"A mapmaker's apprentice discovers sun-summoning powers and enters the glittering, dangerous world of the Grisha in the first Shadow and Bone trilogy novel." },
  { id:352, title:"The Golden Compass", author:"Philip Pullman", isbn:"9780679879244",
    genres:[12,2,17], themes:[0,4,8], year:1995, pages:399, avgRating:4.22,
    description:"Lyra Belacqua and her talking animal daemon travel to the frozen north to rescue kidnapped children in this astonishing anti-clerical fantasy epic." },
  { id:353, title:"Eragon", author:"Christopher Paolini", isbn:"9780375826696",
    genres:[12,2,17], themes:[0,3,5], year:2002, pages:503, avgRating:3.85,
    description:"Written by a 15-year-old, this dragon-rider epic launched the Inheritance Cycle — an epic quest filled with elves, dwarves, and destiny." },
  { id:354, title:"City of Bones", author:"Cassandra Clare", isbn:"9781416914280",
    genres:[12,2,10], themes:[0,2,3], year:2007, pages:485, avgRating:3.91,
    description:"A teenager discovers she's a Shadowhunter — a human born to protect the world from demons — in the action-packed first Mortal Instruments novel." },
  { id:355, title:"The Princess Diaries", author:"Meg Cabot", isbn:"9780380978489",
    genres:[12,5,0], themes:[1,2,9], year:2000, pages:238, avgRating:3.81,
    description:"Mia Thermopolis discovers she's the heir to a tiny European principality — and must juggle royalty lessons, boy trouble, and high school geometry." },
  // MORE CLASSICS
  { id:356, title:"War and Peace", author:"Leo Tolstoy", isbn:"9780140447934",
    genres:[19,13,11], themes:[0,2,3], year:1869, pages:1296, avgRating:4.10,
    description:"The sweeping panorama of Russian society during the Napoleonic Wars — perhaps the greatest novel ever written, tracking five families through war, peace, and love." },
  { id:357, title:"Les Misérables", author:"Victor Hugo", isbn:"9780451419439",
    genres:[19,13,11], themes:[0,5,7], year:1862, pages:1232, avgRating:4.23,
    description:"Jean Valjean, released after 19 years for stealing bread, builds a new life — but the relentless Inspector Javert is always one step behind." },
  { id:358, title:"Bleak House", author:"Charles Dickens", isbn:"9780141439723",
    genres:[19,11,3], themes:[0,4,7], year:1853, pages:1040, avgRating:4.05,
    description:"The case of Jarndyce v Jarndyce has consumed generations of lawyers and devastated all those caught in its web — Dickens's most scathing attack on the law." },
  { id:359, title:"Emma", author:"Jane Austen", isbn:"9780141439587",
    genres:[19,5,11], themes:[2,1,4], year:1815, pages:474, avgRating:4.13,
    description:"Emma Woodhouse, handsome, clever, and rich, is also confidently wrong about almost everything — especially love. Austen's most comedically perfect novel." },
  { id:360, title:"The Picture of Dorian Gray", author:"Oscar Wilde", isbn:"9780141439570",
    genres:[19,11,10], themes:[0,2,4], year:1890, pages:254, avgRating:4.14,
    description:"A beautiful young man wishes his portrait would age instead of him — and it does. A gothic story about vanity, decadence, and the corruption of the soul." },
  // MORE ADVENTURE
  { id:361, title:"Treasure Island", author:"Robert Louis Stevenson", isbn:"9780141321004",
    genres:[17,19,12], themes:[3,6,5], year:1883, pages:292, avgRating:3.82,
    description:"Jim Hawkins, Long John Silver, and a treasure map — the defining adventure story of pirates and peril that never ages." },
  { id:362, title:"Around the World in 80 Days", author:"Jules Verne", isbn:"9781505261547",
    genres:[17,19,1], themes:[3,1,4], year:1872, pages:206, avgRating:3.92,
    description:"Phileas Fogg wagers he can circumnavigate the globe in 80 days. Pursued by a detective who thinks he's a bank robber, he races against time." },
  { id:363, title:"Call of the Wild", author:"Jack London", isbn:"9781402714528",
    genres:[17,0,19], themes:[0,3,5], year:1903, pages:144, avgRating:3.87,
    description:"A domesticated dog is thrust into the brutal Klondike Gold Rush and must locate his primal nature to survive in this powerful, poetic adventure." },
  { id:364, title:"Robinson Crusoe", author:"Daniel Defoe", isbn:"9780192833662",
    genres:[17,19,0], themes:[3,5,8], year:1719, pages:298, avgRating:3.51,
    description:"Shipwrecked on a deserted tropical island for 28 years — the novel that invented the castaway genre and the spiritual journey of solitude." },
  { id:365, title:"Master and Commander", author:"Patrick O'Brian", isbn:"9780393307436",
    genres:[17,13], themes:[3,9,1], year:1969, pages:412, avgRating:4.20,
    description:"The first of 20 novels following Captain Jack Aubrey and ship's surgeon Stephen Maturin during the Napoleonic Wars — the finest naval fiction series ever written." },
  // MORE HORROR / DARK
  { id:366, title:"The Hellbound Heart", author:"Clive Barker", isbn:"9780060973506",
    genres:[10,0], themes:[0,6,2], year:1986, pages:164, avgRating:3.92,
    description:"The novella that spawned Hellraiser — an occult puzzle box opens a doorway to a dimension of exquisite, horrible sensation." },
  { id:367, title:"Annihilation", author:"Jeff VanderMeer", isbn:"9780374104092",
    genres:[10,1,15], themes:[0,6,8], year:2014, pages:195, avgRating:3.69,
    description:"Four women enter Area X — a mysterious, expanding wilderness — and find the expedition has been here before, with catastrophic results." },
  { id:368, title:"Interview with the Vampire", author:"Anne Rice", isbn:"9780345337641",
    genres:[10,13], themes:[0,2,8], year:1976, pages:342, avgRating:4.09,
    description:"A 200-year-old vampire tells a journalist his life story — the creation of the modern literary vampire and a meditation on immortality and regret." },
  { id:369, title:"World War Z", author:"Max Brooks", isbn:"9780307346605",
    genres:[10,18,17], themes:[0,3,7], year:2006, pages:342, avgRating:3.96,
    description:"An oral history of the zombie war, gathered by a UN investigator — told through dozens of global voices in this brilliant, politically satirical horror novel." },
  { id:370, title:"The Exorcist", author:"William Peter Blatty", isbn:"9780062094414",
    genres:[10,0], themes:[0,6,8], year:1971, pages:340, avgRating:3.93,
    description:"A 12-year-old girl is possessed by a demonic entity. Her mother enlists a Jesuit priest in a terrifying battle — still the scariest novel many readers have ever read." },
  // MORE SCIENCE / PHILOSOPHY
  { id:371, title:"The Grand Design", author:"Stephen Hawking & Leonard Mlodinow", isbn:"9780553805376",
    genres:[15,14,6], themes:[4,8], year:2010, pages:208, avgRating:3.71,
    description:"Why does the universe exist? Hawking and Mlodinow argue M-theory is the only candidate for a complete theory of the universe." },
  { id:372, title:"Superforecasting", author:"Philip Tetlock", isbn:"9780804136716",
    genres:[15,6,16], themes:[4,7], year:2015, pages:340, avgRating:4.07,
    description:"How a group of ordinary people became vastly better than experts at predicting world events — the science of making accurate forecasts under uncertainty." },
  { id:373, title:"The Art of War", author:"Sun Tzu", isbn:"9780140455526",
    genres:[14,9,6], themes:[3,4,7], year:-500, pages:128, avgRating:3.97,
    description:"The ancient Chinese military treatise still required reading at every military academy and business school on the planet." },
  { id:374, title:"Letters from a Stoic", author:"Seneca", isbn:"9780140442106",
    genres:[14,6,19], themes:[4,8,5], year:65, pages:272, avgRating:4.14,
    description:"Seneca's collection of 124 letters of moral advice to his friend Lucilius — the most accessible and immediately practical Stoic text." },
  { id:375, title:"The Enchiridion", author:"Epictetus", isbn:"9781503379886",
    genres:[14,6,19], themes:[4,8,5], year:135, pages:74, avgRating:4.03,
    description:"The short manual of Stoic ethics by the ex-slave philosopher — on what is and isn't within our control, still transforming lives 2,000 years later." },
  // MORE LITERARY FICTION
  { id:376, title:"Normal People", author:"Sally Rooney", isbn:"9780571334650",
    genres:[11,5,12], themes:[0,2,9], year:2018, pages:273, avgRating:3.72,
    description:"Connell and Marianne navigate a painful, circling relationship from small-town Ireland to the elite corridors of Trinity College Dublin." },
  { id:377, title:"Lincoln in the Bardo", author:"George Saunders", isbn:"9780812995343",
    genres:[11,0], themes:[0,5,9], year:2017, pages:368, avgRating:3.86,
    description:"The night after his 11-year-old son Willie's burial, Abraham Lincoln visits the cemetery — and the ghosts stuck in the bardo don't want to let Willie go." },
  { id:378, title:"The Goldfinch", author:"Donna Tartt", isbn:"9780316055444",
    genres:[11,3,0], themes:[0,5,9], year:2013, pages:771, avgRating:3.91,
    description:"A boy survives a museum bombing that kills his mother and walks out with a priceless Dutch painting — which will shape the next 15 years of his life." },
  { id:379, title:"A Little Life", author:"Hanya Yanagihara", isbn:"9780804172707",
    genres:[11,0], themes:[0,2,9], year:2015, pages:720, avgRating:4.26,
    description:"Four college friends navigate fame, failure, and extraordinary suffering in New York over several decades. The most devastating novel of the 21st century." },
  { id:380, title:"The Secret History", author:"Donna Tartt", isbn:"9781400031702",
    genres:[11,3,4], themes:[0,4,6], year:1992, pages:559, avgRating:4.08,
    description:"A group of elite classics students at a Vermont college commits murder — the entire novel is about how and why, not whodunit." },
  // MORE SCIENCE
  { id:381, title:"Brief Answers to the Big Questions", author:"Stephen Hawking", isbn:"9781984819192",
    genres:[15,14,6], themes:[4,8,5], year:2018, pages:256, avgRating:4.20,
    description:"Hawking's final book: answers to the ten biggest questions about the universe, humanity's future, and the mind of God. A valedictory masterpiece." },
  { id:382, title:"The Hidden Life of Trees", author:"Peter Wohlleben", isbn:"9781771642484",
    genres:[15,6], themes:[4,8], year:2015, pages:288, avgRating:4.06,
    description:"A German forester reveals the astonishing social networks, parenting behaviour, and communication of forest trees. A book that permanently changes walks in the woods." },
  { id:383, title:"Factfulness", author:"Hans Rosling", isbn:"9781250107817",
    genres:[15,6], themes:[4,5,7], year:2018, pages:342, avgRating:4.36,
    description:"Ten instincts that distort our view of the world — and systematic, fact-based thinking that shows the world is actually better than you think." },
  { id:384, title:"The Innovator's Dilemma", author:"Clayton M. Christensen", isbn:"9781633691780",
    genres:[15,6,8], themes:[4,7], year:1997, pages:336, avgRating:4.06,
    description:"Why successful, well-managed companies fail — and how disruptive innovation consistently topples market leaders from below." },
  { id:385, title:"Surely You're Joking, Mr. Feynman!", author:"Richard Feynman", isbn:"9780393316049",
    genres:[15,7,6], themes:[1,4,5], year:1985, pages:392, avgRating:4.30,
    description:"The Nobel physicist's hilarious and irreverent adventures — picking locks, learning bongo, frequenting strip clubs, and fathering quantum electrodynamics." },
  // FICTION GENERAL
  { id:386, title:"The Goldfinch", author:"Donna Tartt", isbn:"9780316055437",
    genres:[0,11,3], themes:[0,5,9], year:2013, pages:771, avgRating:3.91,
    description:"A portrait of loss, obsession, and survival — Theo navigates his mother's sudden death, the criminal underworld, and the stolen masterpiece that defines his life." },
  { id:387, title:"Where the Crawdads Sing", author:"Delia Owens", isbn:"9780735224292",
    genres:[0,3,5], themes:[0,2,9], year:2018, pages:368, avgRating:4.45,
    description:"A girl raised alone in the North Carolina marshes becomes a murder suspect in this lyrical combination of coming-of-age story, romance, and courtroom thriller." },
  { id:388, title:"The Midnight Library", author:"Matt Haig", isbn:"9780525559474",
    genres:[0,1,11], themes:[0,5,8], year:2020, pages:304, avgRating:3.98,
    description:"Nora Seed finds herself in a library between life and death, each book offering the chance to revisit a life she might have lived if she'd made different choices." },
  { id:389, title:"Eleanor Oliphant is Completely Fine", author:"Gail Honeyman", isbn:"9780735220690",
    genres:[0,11], themes:[0,5,9], year:2017, pages:383, avgRating:4.14,
    description:"Eleanor is almost a cautionary tale in social awkwardness — until a chance friendship begins to thaw a heart frozen by terrible childhood trauma." },
  { id:390, title:"A Man Called Ove", author:"Fredrik Backman", isbn:"9781476738024",
    genres:[0,11], themes:[0,5,9], year:2012, pages:337, avgRating:4.38,
    description:"A curmudgeonly widower tries to die and keeps being interrupted by his new neighbours — a funny, warm, ultimately devastating novel about grief and community." },
  { id:391, title:"The Seven Husbands of Evelyn Hugo", author:"Taylor Jenkins Reid", isbn:"9781501139239",
    genres:[0,5,11], themes:[0,2,7], year:2017, pages:389, avgRating:4.36,
    description:"An aging Hollywood legend unexpectedly summons a young journalist to tell her life story — a dazzling saga of ambition, passion, sacrifice, and LGBTQ love." },
  { id:392, title:"Daisy Jones and The Six", author:"Taylor Jenkins Reid", isbn:"9781524798642",
    genres:[0,5,7], themes:[0,2,5], year:2019, pages:355, avgRating:4.07,
    description:"Told in oral history format, the rise and dissolution of the greatest rock band of the 1970s — and the damaged, brilliant woman who defined them." },
  { id:393, title:"The Alchemist", author:"Paulo Coelho", isbn:"9780062315007",
    genres:[14,17,8], themes:[5,8,3], year:1988, pages:197, avgRating:3.88,
    description:"A shepherd boy travels from Spain to Egypt in search of treasure, learning the Language of the World and finding his Personal Legend." },
  { id:394, title:"Tomorrow, and Tomorrow, and Tomorrow", author:"Gabrielle Zevin", isbn:"9780593321201",
    genres:[0,11], themes:[0,4,5], year:2022, pages:480, avgRating:4.14,
    description:"Two childhood friends become wildly successful video game designers — a love story about creativity, ambition, and the games we play to understand each other." },
  { id:395, title:"The Covenant of Water", author:"Abraham Verghese", isbn:"9780802162175",
    genres:[0,13,11], themes:[0,9,5], year:2023, pages:736, avgRating:4.30,
    description:"Three generations of a family in South India, united by a strange affliction — and the doctors and healers who try to understand it across a century." },
  { id:396, title:"Lessons in Chemistry", author:"Bonnie Garmus", isbn:"9780385547345",
    genres:[0,5,7], themes:[0,1,7], year:2022, pages:390, avgRating:4.24,
    description:"A female chemist in the 1960s is fired and becomes a cooking show host — teaching her audience chemistry, feminism, and their own radical potential." },
  { id:397, title:"Demon Copperhead", author:"Barbara Kingsolver", isbn:"9780063251922",
    genres:[11,0,19], themes:[0,5,9], year:2022, pages:548, avgRating:4.15,
    description:"David Copperfield reimagined as an Appalachian boy navigating foster care, poverty, and the opioid crisis in modern Virginia — Pulitzer Prize 2023." },
  { id:398, title:"The Covenant", author:"Naomi Novik", isbn:"9780593496329",
    genres:[2,12,17], themes:[0,2,8], year:2022, pages:512, avgRating:4.10,
    description:"A school for wizards, chosen champions, and a labyrinthine death maze — Novik reinvents the deadly magical school with stunning brilliance." },
  { id:399, title:"Fourth Wing", author:"Rebecca Yarros", isbn:"9781649374042",
    genres:[2,5,17], themes:[0,2,3], year:2023, pages:517, avgRating:4.25,
    description:"A woman enters the brutal elite war college for dragon riders — and is challenged physically, academically, and romantically by the most dangerous rider there." },
  { id:400, title:"Happy Place (Redux)", author:"Emily Henry", isbn:"9780593441305",
    genres:[5,0,11], themes:[2,1,9], year:2023, pages:400, avgRating:3.96,
    description:"An unforgettable seaside summer. A decaying relationship. Six friends who don't yet know that everything is about to change — Henry at her most emotionally layered." },
];
window.BOOKS_PART5 = BOOKS_PART5;
